### ISSUE TITLE
Server crash with monk mod 1.3

### ISSUE THREAD

**Issue by Lordeath19** [rwtema/Monk-Mod#20]
How does one install the mod on a server?

 

 

I am running the latest version (1.3) and when running it on a server it gives me this error:

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/BufferBuilder

 

which means it's a client only mod (as gathered by the forums).

 

for more info :https://pastebin.com/GHzXpAvW

**Comment by CplPibald** [comment]
Confirmed.  Seeing this crash on server start after upgrading from 1.2 to 1.3

**Comment by gradytrain** [comment]
I think this might be related to #19 because I got it when I was on version 1.3.

**Comment by Darkmega18** [comment]
This. I have this also. :V

**Comment by Lordeath19** [comment]
I managed to fix it, in the preInit function inside the MonkMod.java, move line 84 above line 98 (MonkTextures.init();)

That fixed it for me

**Comment by Lordeath19** [comment]
lol oops should probably close this now
